services:
  db:
    image: postgres:15-alpine
    container_name: crud_pacientes_db
    environment:
      POSTGRES_DB: crud_pacientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crud_pacientes"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: crud_pacientes_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crud_pacientes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: